version: '3.8'
services:

  leeks:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=password
      - FLASK_GITHUB_CLIENT_ID=
      - FLASK_GITHUB_CLIENT_SECRET=

  neo4j:
    image: neo4j:latest
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - neo4j-data:/data/
    environment:
      - NEO4J_AUTH=none

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=fifemon-graphql-datasource

  # slides:
  #   image: cloudogu/reveal.js:dev
  #   volumes:
  #     - ./slides:/reveal/docs/slides
  #   environment:
  #     - TITLE=SaaS - Security as a SecondThought
  #     - ADDITIONAL_REVEAL_OPTIONS=transition:'none'
  #     - THEME_CSS=cloudogu-black.css
  #   ports:
  #     - 8000:8000
  #     - 35729:35729

volumes:
  grafana-storage:
  neo4j-data: