version: '3.8'
services:

  savoy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=password

  age:
    image: apache/age:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local